#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from LAB02-Nieto-Utria-Gonzalez.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "LAB02-Nieto-Utria-Gonzalez.y"

extern int yylex();
#include <stdio.h>
#include <string.h>



extern int contLineas;

int ant=-1;
int conterror=0;
extern FILE *yyin, *yyout;

void yyerror(const char *str)
{
    if(ant!=contLineas){
        fprintf(yyout, "Error sintáctico en línea número : %d\n", contLineas);
        ant=contLineas;
        conterror=conterror+1;
    }
}

int yywrap()
{
    return 1;
}


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	COMA	258
#define	CTEREALSIGNO	259
#define	CTEREALSINSIGNO	260
#define	CTEENTSIGNO	261
#define	CTEENTSINSIGNO	262
#define	CTECADENA	263
#define	PUNTOYCOMA	264
#define	ELSE	265
#define	IF	266
#define	FOR	267
#define	WHILE	268
#define	DOUBLE	269
#define	INT	270
#define	STRING	271
#define	CHAR	272
#define	NEW	273
#define	PUBLIC	274
#define	CLASS	275
#define	STATIC	276
#define	VOID	277
#define	ID	278
#define	COMENTARIOSIMPLE	279
#define	COMENTARIOCOMPLETO	280
#define	OPMULT	281
#define	OPSUM	282
#define	OPSUS	283
#define	OPDIV	284
#define	OPASIGN	285
#define	OPMOD	286
#define	OPMASMAS	287
#define	OPMENOSMENOS	288
#define	OPPORASIGN	289
#define	OPDIVASIGN	290
#define	OPSUMASIGN	291
#define	OPSUSASIGN	292
#define	LLAVEA	293
#define	LLAVEC	294
#define	PARENTA	295
#define	PARENTC	296
#define	CORCHETEA	297
#define	CORCHETEC	298
#define	IGUAL	299
#define	ARRAY	300
#define	OPMENORIGUAL	301
#define	OPMAYORIGUAL	302
#define	OPDIFERENTE	303
#define	OPMAYOR	304
#define	OPMENOR	305
#define	OPY	306
#define	OPO	307
#define	OPNO	308
#define	VACIO	309


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int COMA;
static const int CTEREALSIGNO;
static const int CTEREALSINSIGNO;
static const int CTEENTSIGNO;
static const int CTEENTSINSIGNO;
static const int CTECADENA;
static const int PUNTOYCOMA;
static const int ELSE;
static const int IF;
static const int FOR;
static const int WHILE;
static const int DOUBLE;
static const int INT;
static const int STRING;
static const int CHAR;
static const int NEW;
static const int PUBLIC;
static const int CLASS;
static const int STATIC;
static const int VOID;
static const int ID;
static const int COMENTARIOSIMPLE;
static const int COMENTARIOCOMPLETO;
static const int OPMULT;
static const int OPSUM;
static const int OPSUS;
static const int OPDIV;
static const int OPASIGN;
static const int OPMOD;
static const int OPMASMAS;
static const int OPMENOSMENOS;
static const int OPPORASIGN;
static const int OPDIVASIGN;
static const int OPSUMASIGN;
static const int OPSUSASIGN;
static const int LLAVEA;
static const int LLAVEC;
static const int PARENTA;
static const int PARENTC;
static const int CORCHETEA;
static const int CORCHETEC;
static const int IGUAL;
static const int ARRAY;
static const int OPMENORIGUAL;
static const int OPMAYORIGUAL;
static const int OPDIFERENTE;
static const int OPMAYOR;
static const int OPMENOR;
static const int OPY;
static const int OPO;
static const int OPNO;
static const int VACIO;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,COMA=258
	,CTEREALSIGNO=259
	,CTEREALSINSIGNO=260
	,CTEENTSIGNO=261
	,CTEENTSINSIGNO=262
	,CTECADENA=263
	,PUNTOYCOMA=264
	,ELSE=265
	,IF=266
	,FOR=267
	,WHILE=268
	,DOUBLE=269
	,INT=270
	,STRING=271
	,CHAR=272
	,NEW=273
	,PUBLIC=274
	,CLASS=275
	,STATIC=276
	,VOID=277
	,ID=278
	,COMENTARIOSIMPLE=279
	,COMENTARIOCOMPLETO=280
	,OPMULT=281
	,OPSUM=282
	,OPSUS=283
	,OPDIV=284
	,OPASIGN=285
	,OPMOD=286
	,OPMASMAS=287
	,OPMENOSMENOS=288
	,OPPORASIGN=289
	,OPDIVASIGN=290
	,OPSUMASIGN=291
	,OPSUSASIGN=292
	,LLAVEA=293
	,LLAVEC=294
	,PARENTA=295
	,PARENTC=296
	,CORCHETEA=297
	,CORCHETEC=298
	,IGUAL=299
	,ARRAY=300
	,OPMENORIGUAL=301
	,OPMAYORIGUAL=302
	,OPDIFERENTE=303
	,OPMAYOR=304
	,OPMENOR=305
	,OPY=306
	,OPO=307
	,OPNO=308
	,VACIO=309


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::COMA=258;
const int YY_parse_CLASS::CTEREALSIGNO=259;
const int YY_parse_CLASS::CTEREALSINSIGNO=260;
const int YY_parse_CLASS::CTEENTSIGNO=261;
const int YY_parse_CLASS::CTEENTSINSIGNO=262;
const int YY_parse_CLASS::CTECADENA=263;
const int YY_parse_CLASS::PUNTOYCOMA=264;
const int YY_parse_CLASS::ELSE=265;
const int YY_parse_CLASS::IF=266;
const int YY_parse_CLASS::FOR=267;
const int YY_parse_CLASS::WHILE=268;
const int YY_parse_CLASS::DOUBLE=269;
const int YY_parse_CLASS::INT=270;
const int YY_parse_CLASS::STRING=271;
const int YY_parse_CLASS::CHAR=272;
const int YY_parse_CLASS::NEW=273;
const int YY_parse_CLASS::PUBLIC=274;
const int YY_parse_CLASS::CLASS=275;
const int YY_parse_CLASS::STATIC=276;
const int YY_parse_CLASS::VOID=277;
const int YY_parse_CLASS::ID=278;
const int YY_parse_CLASS::COMENTARIOSIMPLE=279;
const int YY_parse_CLASS::COMENTARIOCOMPLETO=280;
const int YY_parse_CLASS::OPMULT=281;
const int YY_parse_CLASS::OPSUM=282;
const int YY_parse_CLASS::OPSUS=283;
const int YY_parse_CLASS::OPDIV=284;
const int YY_parse_CLASS::OPASIGN=285;
const int YY_parse_CLASS::OPMOD=286;
const int YY_parse_CLASS::OPMASMAS=287;
const int YY_parse_CLASS::OPMENOSMENOS=288;
const int YY_parse_CLASS::OPPORASIGN=289;
const int YY_parse_CLASS::OPDIVASIGN=290;
const int YY_parse_CLASS::OPSUMASIGN=291;
const int YY_parse_CLASS::OPSUSASIGN=292;
const int YY_parse_CLASS::LLAVEA=293;
const int YY_parse_CLASS::LLAVEC=294;
const int YY_parse_CLASS::PARENTA=295;
const int YY_parse_CLASS::PARENTC=296;
const int YY_parse_CLASS::CORCHETEA=297;
const int YY_parse_CLASS::CORCHETEC=298;
const int YY_parse_CLASS::IGUAL=299;
const int YY_parse_CLASS::ARRAY=300;
const int YY_parse_CLASS::OPMENORIGUAL=301;
const int YY_parse_CLASS::OPMAYORIGUAL=302;
const int YY_parse_CLASS::OPDIFERENTE=303;
const int YY_parse_CLASS::OPMAYOR=304;
const int YY_parse_CLASS::OPMENOR=305;
const int YY_parse_CLASS::OPY=306;
const int YY_parse_CLASS::OPO=307;
const int YY_parse_CLASS::OPNO=308;
const int YY_parse_CLASS::VACIO=309;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		286
#define	YYFLAG		-32768
#define	YYNTBASE	55

#define YYTRANSLATE(x) ((unsigned)(x) <= 309 ? yytranslate[x] : 89)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     6,    12,    17,    21,    24,    27,    29,    39,    49,
    58,    66,    73,    79,    84,    87,    90,    92,    95,    98,
   101,   103,   105,   107,   109,   112,   115,   118,   121,   125,
   129,   133,   138,   143,   148,   151,   155,   157,   159,   161,
   163,   166,   169,   172,   175,   179,   183,   189,   193,   198,
   203,   208,   213,   216,   221,   224,   227,   230,   234,   238,
   240,   244,   248,   251,   254,   258,   261,   264,   267,   270,
   273,   277,   279,   281,   287,   293,   297,   301,   304,   306,
   308,   310,   312,   314,   316,   318,   320,   322,   324,   326,
   330,   332,   336,   340,   344,   348,   352,   356,   361,   363,
   365,   367,   369,   371,   373,   375,   377,   383,   388,   392,
   400,   403,   407,   414,   420,   425,   430,   434,   437,   442,
   447,   451
};

static const short yyrhs[] = {    19,
    20,    23,    38,    56,     0,     1,    20,    23,    38,    56,
     0,     1,    23,    38,    56,     0,     1,    38,    56,     0,
     1,    56,     0,    57,    39,     0,    39,     0,    19,    21,
    22,    23,    40,    59,    41,    38,    58,     0,     1,    21,
    22,    23,    40,    59,    41,    38,    58,     0,     1,    22,
    23,    40,    59,    41,    38,    58,     0,     1,    23,    40,
    59,    41,    38,    58,     0,     1,    40,    59,    41,    38,
    58,     0,     1,    59,    41,    38,    58,     0,     1,    41,
    38,    58,     0,     1,    58,     0,    64,    39,     0,    39,
     0,    60,    23,     0,    61,    23,     0,     1,    23,     0,
    16,     0,    17,     0,    15,     0,    14,     0,    16,    63,
     0,    17,    63,     0,    15,    63,     0,    14,    63,     0,
    42,    23,    43,     0,    42,     6,    43,     0,    42,     7,
    43,     0,    62,    42,     6,    43,     0,    62,    42,     7,
    43,     0,    62,    42,    23,    43,     0,    42,    43,     0,
    63,    42,    43,     0,    65,     0,    82,     0,    84,     0,
    86,     0,    64,    65,     0,    64,    82,     0,    64,    84,
     0,    64,    86,     0,    60,    23,     9,     0,    61,    23,
     9,     0,    61,    23,    30,    68,     9,     0,    60,    67,
     9,     0,    60,    23,    66,     9,     0,    61,    23,    66,
     9,     0,    60,    67,    66,     9,     0,    61,    67,    66,
     9,     0,    67,     9,     0,    23,    30,    68,     9,     0,
     1,     9,     0,     3,    67,     0,     3,    23,     0,    66,
     3,    23,     0,    66,     3,    67,     0,    69,     0,    23,
    30,     8,     0,    18,    60,    62,     0,    23,    70,     0,
    23,    32,     0,    23,    30,    71,     0,    23,    33,     0,
    34,    71,     0,    36,    71,     0,    37,    71,     0,    35,
    71,     0,    40,    71,    41,     0,    72,     0,    74,     0,
    71,    76,    40,    71,    41,     0,    71,    75,    40,    71,
    41,     0,    71,    76,    72,     0,    71,    76,    74,     0,
    71,    74,     0,    73,     0,    23,     0,     7,     0,     5,
     0,     4,     0,     6,     0,    27,     0,    28,     0,    26,
     0,    29,     0,    31,     0,    77,    79,    78,     0,    78,
     0,    23,    53,     8,     0,    23,    51,     8,     0,    23,
    79,    23,     0,    71,    81,    71,     0,    71,    80,    71,
     0,    40,    78,    41,     0,    53,    40,    78,    41,     0,
    51,     0,    52,     0,    48,     0,    44,     0,    46,     0,
    50,     0,    49,     0,    47,     0,    12,    40,    60,    67,
    83,     0,    12,    40,    67,    83,     0,     1,    38,    58,
     0,     9,    77,     9,    69,    41,    38,    58,     0,     1,
    58,     0,    13,    40,    85,     0,    13,    40,    23,    41,
    38,    58,     0,     1,    40,    41,    38,    58,     0,    77,
    41,    38,    58,     0,     1,    41,    38,    58,     0,    11,
    40,    87,     0,    86,    88,     0,    77,    41,    38,    58,
     0,    23,    41,    38,    58,     0,     1,    38,    58,     0,
    10,    38,    58,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    39,    41,    42,    43,    44,    47,    48,    51,    53,    54,
    55,    56,    57,    58,    59,    63,    64,    67,    68,    69,
    72,    73,    74,    75,    79,    80,    81,    82,    85,    86,
    87,    88,    89,    90,    93,    94,    97,    98,    99,   100,
   101,   102,   103,   104,   107,   108,   109,   110,   111,   112,
   113,   114,   115,   116,   117,   120,   121,   122,   123,   125,
   126,   129,   132,   133,   134,   135,   138,   139,   140,   141,
   144,   145,   146,   147,   148,   149,   150,   151,   154,   155,
   158,   159,   162,   163,   165,   166,   168,   169,   170,   173,
   174,   177,   178,   179,   180,   181,   182,   183,   186,   187,
   190,   191,   194,   195,   196,   197,   200,   201,   202,   204,
   205,   208,   209,   210,   212,   213,   216,   217,   219,   220,
   221,   224
};

static const char * const yytname[] = {   "$","error","$illegal.","COMA","CTEREALSIGNO",
"CTEREALSINSIGNO","CTEENTSIGNO","CTEENTSINSIGNO","CTECADENA","PUNTOYCOMA","ELSE",
"IF","FOR","WHILE","DOUBLE","INT","STRING","CHAR","NEW","PUBLIC","CLASS","STATIC",
"VOID","ID","COMENTARIOSIMPLE","COMENTARIOCOMPLETO","OPMULT","OPSUM","OPSUS",
"OPDIV","OPASIGN","OPMOD","OPMASMAS","OPMENOSMENOS","OPPORASIGN","OPDIVASIGN",
"OPSUMASIGN","OPSUSASIGN","LLAVEA","LLAVEC","PARENTA","PARENTC","CORCHETEA",
"CORCHETEC","IGUAL","ARRAY","OPMENORIGUAL","OPMAYORIGUAL","OPDIFERENTE","OPMAYOR",
"OPMENOR","OPY","OPO","OPNO","VACIO","clase","clase2","metodomain","cerrarbloque",
"parametro","tipo","tipovector","dimensionval","dimensionparam","bloque","declaracion",
"declaracion2","asignacion","valorvector","valorasigarit","operadoresaritasig",
"operacion","valoroperacion","constssinsignoarit","constsconsignoarit","operadoressumasus",
"operadoresarit","condicion","verificacion","operadoreslogconcat","operadoreslogcompa",
"operadoreslogarit","structfor","for2","structwhile","structwhile2","strucif",
"strucif2","strucifelse",""
};
#endif

static const short yyr1[] = {     0,
    55,    55,    55,    55,    55,    56,    56,    57,    57,    57,
    57,    57,    57,    57,    57,    58,    58,    59,    59,    59,
    60,    60,    60,    60,    61,    61,    61,    61,    62,    62,
    62,    62,    62,    62,    63,    63,    64,    64,    64,    64,
    64,    64,    64,    64,    65,    65,    65,    65,    65,    65,
    65,    65,    65,    65,    65,    66,    66,    66,    66,    67,
    67,    68,    69,    69,    69,    69,    70,    70,    70,    70,
    71,    71,    71,    71,    71,    71,    71,    71,    72,    72,
    73,    73,    74,    74,    75,    75,    76,    76,    76,    77,
    77,    78,    78,    78,    78,    78,    78,    78,    79,    79,
    80,    80,    81,    81,    81,    81,    82,    82,    82,    83,
    83,    84,    84,    84,    85,    85,    86,    86,    87,    87,
    87,    88
};

static const short yyr2[] = {     0,
     5,     5,     4,     3,     2,     2,     1,     9,     9,     8,
     7,     6,     5,     4,     2,     2,     1,     2,     2,     2,
     1,     1,     1,     1,     2,     2,     2,     2,     3,     3,
     3,     4,     4,     4,     2,     3,     1,     1,     1,     1,
     2,     2,     2,     2,     3,     3,     5,     3,     4,     4,
     4,     4,     2,     4,     2,     2,     2,     3,     3,     1,
     3,     3,     2,     2,     3,     2,     2,     2,     2,     2,
     3,     1,     1,     5,     5,     3,     3,     2,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     3,
     1,     3,     3,     3,     3,     3,     3,     4,     1,     1,
     1,     1,     1,     1,     1,     1,     5,     4,     3,     7,
     2,     3,     6,     5,     4,     4,     3,     2,     4,     4,
     3,     3
};

static const short yydefact[] = {     0,
     0,     0,     0,     0,     0,     0,     0,     7,     5,     0,
     0,     0,     0,     0,     0,    24,    23,    21,    22,     0,
     0,     0,    17,     0,     0,    15,     0,     0,     0,     0,
    37,     0,    60,    38,    39,    40,     0,     0,     0,     4,
     6,     0,    55,    20,     0,     0,     0,     0,     0,     0,
    28,    27,    25,    26,     0,     0,     0,    64,    66,     0,
     0,     0,     0,     0,    63,     0,     0,     0,     0,     0,
     0,    18,     0,    19,     0,     0,     0,    16,     0,     0,
    41,    42,    43,    44,    53,     0,   118,     0,     0,     3,
     0,   109,     0,     0,    83,    82,    84,    81,    80,     0,
     0,     0,    72,    79,    73,     0,    91,   117,    24,    23,
    21,    22,     0,     0,     0,     0,    80,     0,   112,    35,
     0,     0,     0,    61,     0,    80,     0,     0,    65,    67,
    70,    68,    69,     0,     0,    18,    19,    14,     0,     0,
    45,     0,     0,    48,     0,    46,     0,     0,     0,     0,
     0,     0,     0,     2,     1,     0,     0,     0,    99,   100,
     0,     0,    80,     0,     0,     0,    87,    85,    86,    88,
    89,   102,   103,   106,   101,   105,   104,    78,     0,     0,
     0,     0,     0,    99,     0,     0,     0,     0,   108,     0,
     0,     0,    36,     0,     0,     0,     0,    54,     0,     0,
    13,    57,    56,     0,    49,    51,     0,    50,    52,   122,
     0,   114,   121,     0,    93,    92,    94,    71,    97,     0,
     0,     0,    76,    77,    96,    95,     0,    90,   107,   111,
     0,     0,     0,     0,     0,     0,     0,    62,     0,    12,
    58,    59,    47,     0,   120,    98,     0,     0,   119,     0,
   116,   113,   115,     0,     0,     0,     0,     0,     0,    11,
     0,    75,    74,     0,     0,     0,    10,    30,    31,    29,
     0,     0,     0,     0,     0,     0,     9,    32,    33,    34,
     8,     0,   110,     0,     0,     0
};

static const short yydefgoto[] = {   284,
     9,    10,    26,    27,    79,    80,   238,    51,    30,    31,
   143,    32,   128,    33,    65,   102,   103,   104,   105,   179,
   180,   106,   107,   162,   181,   182,    34,   189,    35,   119,
    36,   108,    87
};

static const short yypact[] = {    26,
    61,    -3,   255,    15,     3,   -10,    12,-32768,-32768,    11,
    49,    14,    45,    50,    53,    66,    66,    66,    66,   102,
   108,   368,-32768,   169,    84,-32768,    97,   124,   136,   191,
-32768,   152,-32768,-32768,-32768,   153,   142,   129,    12,-32768,
-32768,   133,-32768,-32768,   274,   127,   109,   295,   173,   132,
   134,   134,   134,   134,   149,   141,   322,-32768,-32768,   113,
   113,   113,   113,   169,-32768,   170,   154,   174,   175,   274,
   163,   351,    46,   360,   212,    25,   377,-32768,   202,   204,
-32768,-32768,-32768,   153,-32768,   190,-32768,   215,    12,-32768,
    12,-32768,   197,   201,-32768,-32768,-32768,-32768,    99,    52,
   207,   214,-32768,-32768,-32768,   -19,-32768,-32768,-32768,-32768,
-32768,-32768,   385,   221,    73,   209,   171,    27,-32768,-32768,
   216,   208,   169,-32768,   317,-32768,   113,   248,   347,   347,
   347,   347,   347,   224,   235,-32768,-32768,-32768,   274,   251,
-32768,   342,    74,-32768,   100,-32768,   322,   130,   151,   351,
   360,   274,   240,-32768,-32768,   274,   274,   254,   285,-32768,
   291,   282,   231,   205,   266,    52,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   268,   332,
   113,   113,   276,-32768,    52,    73,   274,    52,-32768,   277,
   279,   281,-32768,   169,   283,   302,   117,-32768,   314,   274,
-32768,   385,-32768,   333,-32768,-32768,   348,-32768,-32768,-32768,
   169,-32768,-32768,   274,-32768,-32768,-32768,-32768,-32768,   318,
   113,   113,-32768,-32768,   347,   347,   274,-32768,-32768,-32768,
     9,   274,   274,   274,   320,   326,    41,   316,   274,-32768,
   385,-32768,-32768,   325,-32768,-32768,   275,   294,-32768,   344,
-32768,-32768,-32768,   330,   274,   327,   328,   334,    81,-32768,
   341,-32768,-32768,   393,   339,   274,-32768,-32768,-32768,-32768,
   346,   356,   363,   274,   113,   353,-32768,-32768,-32768,-32768,
-32768,   274,-32768,   416,   424,-32768
};

static const short yypgoto[] = {-32768,
     7,-32768,   -45,   -21,     5,     6,-32768,   324,-32768,   401,
   -54,   -13,   286,   182,-32768,   -56,   256,-32768,   -91,-32768,
-32768,   -47,   -90,   -94,-32768,-32768,   404,   249,   407,-32768,
   408,-32768,-32768
};


#define	YYLAST		438


static const short yytable[] = {    92,
   129,   118,    67,   130,   131,   132,   133,    28,    29,   165,
   178,   185,     3,    40,    73,    75,    11,   250,   145,   148,
   149,   183,    43,   185,   138,    38,     1,    39,    68,    69,
     4,   184,   160,    43,   115,    37,    44,   178,   178,   178,
   178,   178,   134,   164,     2,    90,   256,   257,   140,    41,
     8,    45,   114,    46,   144,    95,    96,    97,    98,   184,
   160,     3,    45,   258,    46,    73,    75,   192,    68,    69,
   197,    42,   178,   187,   163,   220,   204,   184,   160,     4,
     5,   188,   205,     6,    47,   129,   271,   272,   224,    48,
   129,   100,    49,   201,   228,   154,   148,   155,     7,     8,
   186,   195,   204,   273,   101,   178,   210,    50,   206,    94,
   212,   213,    95,    96,    97,    98,    95,    96,    97,    98,
    95,    70,    97,    55,   225,   226,   203,    68,    69,   196,
    56,    99,   204,   178,   178,   126,   185,    71,   208,   158,
   231,   230,   167,   168,   169,   170,    72,   171,   100,   159,
   160,   161,   127,   204,   240,   178,   178,   218,    74,   209,
    85,   101,    86,    88,   247,   248,    89,    93,   245,    66,
    91,   122,   235,   116,   120,   121,    95,    96,    97,    98,
   123,   249,    16,    17,    18,    19,   251,   252,   253,   244,
   242,    76,    44,   260,   135,   117,   136,   137,    68,    69,
   139,    13,    14,    15,    16,    17,    18,    19,    95,   267,
    97,   191,   100,    77,   140,    68,    69,    95,   129,    97,
   277,   159,   160,   161,   150,   101,   151,   152,   281,    78,
   167,   168,   169,   170,   156,   171,   283,   153,   157,   167,
   168,   169,   170,   113,   171,   218,   166,   194,   172,   190,
   173,   174,   175,   176,   177,    12,   198,   172,   193,   173,
   174,   175,   176,   177,   199,    13,    14,    15,    16,    17,
    18,    19,   200,   202,    76,    20,    21,    22,    95,   211,
    97,   159,   160,   161,    13,    14,    15,    16,    17,    18,
    19,   214,   215,    23,    24,    25,    77,    95,   216,    97,
   167,   168,   169,   170,   217,   171,   219,   221,   109,   110,
   111,   112,    23,   227,   232,   262,   233,   113,   234,   167,
   168,   169,   170,   236,   171,    95,    96,    97,    98,   124,
   109,   110,   111,   112,   263,    95,    96,    97,    98,   125,
    52,    53,    54,   237,   126,    95,    96,    97,    98,   124,
    95,   239,    97,   140,   126,   241,   243,   259,   246,   141,
   254,   127,   140,   255,   126,   261,   264,   266,   146,   268,
   269,   222,   167,   168,   169,   170,   270,   171,   274,   276,
   142,   127,    58,    59,    60,    61,    62,    63,   278,   147,
   282,    58,    59,    60,    61,    62,    63,    57,   279,    58,
    59,    60,    61,    62,    63,   280,    57,    64,    58,    59,
    60,    61,    62,    63,   142,   285,    58,    59,    60,    61,
    62,    63,   275,   286,    58,    59,    60,    61,    62,    63,
    81,   265,   207,    82,   229,   223,    83,    84
};

static const short yycheck[] = {    45,
    57,    49,    24,    60,    61,    62,    63,     3,     3,   100,
   102,   106,     1,     7,    28,    29,    20,     9,    73,    74,
    75,    41,     9,   118,    70,    23,     1,    38,    24,    24,
    19,    51,    52,     9,    48,    21,    23,   129,   130,   131,
   132,   133,    64,   100,    19,    39,     6,     7,     3,    39,
    39,    38,    48,    40,     9,     4,     5,     6,     7,    51,
    52,     1,    38,    23,    40,    79,    80,    41,    64,    64,
   127,    23,   164,     1,    23,   166,     3,    51,    52,    19,
    20,     9,     9,    23,    40,   142,     6,     7,   180,    40,
   147,    40,    40,   139,   185,    89,   151,    91,    38,    39,
   114,   123,     3,    23,    53,   197,   152,    42,     9,     1,
   156,   157,     4,     5,     6,     7,     4,     5,     6,     7,
     4,    38,     6,    22,   181,   182,   140,   123,   123,   125,
    23,    23,     3,   225,   226,    23,   231,    41,     9,    41,
   188,   187,    26,    27,    28,    29,    23,    31,    40,    51,
    52,    53,    40,     3,   200,   247,   248,    41,    23,     9,
     9,    53,    10,    22,   221,   222,    38,    41,   214,     1,
    38,    23,   194,     1,    43,    42,     4,     5,     6,     7,
    40,   227,    14,    15,    16,    17,   232,   233,   234,   211,
   204,     1,    23,   239,    41,    23,    23,    23,   194,   194,
    38,    11,    12,    13,    14,    15,    16,    17,     4,   255,
     6,    41,    40,    23,     3,   211,   211,     4,   275,     6,
   266,    51,    52,    53,    23,    53,    23,    38,   274,    39,
    26,    27,    28,    29,    38,    31,   282,    23,    38,    26,
    27,    28,    29,    23,    31,    41,    40,    40,    44,    41,
    46,    47,    48,    49,    50,     1,     9,    44,    43,    46,
    47,    48,    49,    50,    41,    11,    12,    13,    14,    15,
    16,    17,    38,    23,     1,    21,    22,    23,     4,    40,
     6,    51,    52,    53,    11,    12,    13,    14,    15,    16,
    17,    38,     8,    39,    40,    41,    23,     4,     8,     6,
    26,    27,    28,    29,    23,    31,    41,    40,    14,    15,
    16,    17,    39,    38,    38,    41,    38,    23,    38,    26,
    27,    28,    29,    41,    31,     4,     5,     6,     7,     8,
    14,    15,    16,    17,    41,     4,     5,     6,     7,    18,
    17,    18,    19,    42,    23,     4,     5,     6,     7,     8,
     4,    38,     6,     3,    23,    23,     9,    42,    41,     9,
    41,    40,     3,    38,    23,    41,    23,    38,     9,    43,
    43,    40,    26,    27,    28,    29,    43,    31,    38,    41,
    30,    40,    32,    33,    34,    35,    36,    37,    43,    30,
    38,    32,    33,    34,    35,    36,    37,    30,    43,    32,
    33,    34,    35,    36,    37,    43,    30,    40,    32,    33,
    34,    35,    36,    37,    30,     0,    32,    33,    34,    35,
    36,    37,    30,     0,    32,    33,    34,    35,    36,    37,
    30,   250,   147,    30,   186,   180,    30,    30
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 229 "LAB02-Nieto-Utria-Gonzalez.y"


int main(int argc, char* argv[])
{
    if(argc==2){
        yyin = fopen(argv[1], "r");
        yyout = fopen("saliday.txt","w");
        fprintf(yyout, "Prueba con el archivo de entrada\n");
        if (yyin != NULL){
            while(!feof(yyin)){
                yyparse();
            }
            if(conterror == 0){
                fprintf(yyout, "Bien");
            }
        }
    }
}



