#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from LAB01-Nieto-Utria-Gonzalez.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "LAB01-Nieto-Utria-Gonzalez.y"

#include <stdio.h>
#include <string.h>


extern int contLineas;

int ant=-1;

void yyerror(const char *str)
{

    if(ant!=contLineas){
    fprintf(stderr, "error: %s, %d\n", str, contLineas);
        ant=contLineas;
    }
}

int yywrap()
{
    return 1;
}

int main(int argc, char* argv[])
{
    extern FILE *yyin, *yyout;
  
    yyin = fopen("entrada.java", "r");
  
    yyout = fopen("salida.txt","w");

    while(!feof(yyin)){
    yyparse();
    }
}

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	COMA	258
#define	CTEREALSIGNO	259
#define	CTEREALSINSIGNO	260
#define	CTEENTSIGNO	261
#define	CTEENTSINSIGNO	262
#define	CTECADENA	263
#define	PUNTOYCOMA	264
#define	ELSE	265
#define	IF	266
#define	FOR	267
#define	WHILE	268
#define	DOUBLE	269
#define	INT	270
#define	STRING	271
#define	CHAR	272
#define	NEW	273
#define	PUBLIC	274
#define	CLASS	275
#define	STATIC	276
#define	VOID	277
#define	ID	278
#define	COMENTARIOSIMPLE	279
#define	COMENTARIOCOMPLETO	280
#define	OPMULT	281
#define	OPSUM	282
#define	OPSUS	283
#define	OPDIV	284
#define	OPASIGN	285
#define	OPMOD	286
#define	OPMASMAS	287
#define	OPMENOSMENOS	288
#define	OPPORASIGN	289
#define	OPDIVASIGN	290
#define	OPSUMASIGN	291
#define	OPSUSASIGN	292
#define	LLAVEA	293
#define	LLAVEC	294
#define	PARENTA	295
#define	PARENTC	296
#define	CORCHETEA	297
#define	CORCHETEC	298
#define	IGUAL	299
#define	ARRAY	300
#define	OPMENORIGUAL	301
#define	OPMAYORIGUAL	302
#define	OPDIFERENTE	303
#define	OPMAYOR	304
#define	OPMENOR	305
#define	OPY	306
#define	OPO	307
#define	OPNO	308
#define	VACIO	309


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int COMA;
static const int CTEREALSIGNO;
static const int CTEREALSINSIGNO;
static const int CTEENTSIGNO;
static const int CTEENTSINSIGNO;
static const int CTECADENA;
static const int PUNTOYCOMA;
static const int ELSE;
static const int IF;
static const int FOR;
static const int WHILE;
static const int DOUBLE;
static const int INT;
static const int STRING;
static const int CHAR;
static const int NEW;
static const int PUBLIC;
static const int CLASS;
static const int STATIC;
static const int VOID;
static const int ID;
static const int COMENTARIOSIMPLE;
static const int COMENTARIOCOMPLETO;
static const int OPMULT;
static const int OPSUM;
static const int OPSUS;
static const int OPDIV;
static const int OPASIGN;
static const int OPMOD;
static const int OPMASMAS;
static const int OPMENOSMENOS;
static const int OPPORASIGN;
static const int OPDIVASIGN;
static const int OPSUMASIGN;
static const int OPSUSASIGN;
static const int LLAVEA;
static const int LLAVEC;
static const int PARENTA;
static const int PARENTC;
static const int CORCHETEA;
static const int CORCHETEC;
static const int IGUAL;
static const int ARRAY;
static const int OPMENORIGUAL;
static const int OPMAYORIGUAL;
static const int OPDIFERENTE;
static const int OPMAYOR;
static const int OPMENOR;
static const int OPY;
static const int OPO;
static const int OPNO;
static const int VACIO;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,COMA=258
	,CTEREALSIGNO=259
	,CTEREALSINSIGNO=260
	,CTEENTSIGNO=261
	,CTEENTSINSIGNO=262
	,CTECADENA=263
	,PUNTOYCOMA=264
	,ELSE=265
	,IF=266
	,FOR=267
	,WHILE=268
	,DOUBLE=269
	,INT=270
	,STRING=271
	,CHAR=272
	,NEW=273
	,PUBLIC=274
	,CLASS=275
	,STATIC=276
	,VOID=277
	,ID=278
	,COMENTARIOSIMPLE=279
	,COMENTARIOCOMPLETO=280
	,OPMULT=281
	,OPSUM=282
	,OPSUS=283
	,OPDIV=284
	,OPASIGN=285
	,OPMOD=286
	,OPMASMAS=287
	,OPMENOSMENOS=288
	,OPPORASIGN=289
	,OPDIVASIGN=290
	,OPSUMASIGN=291
	,OPSUSASIGN=292
	,LLAVEA=293
	,LLAVEC=294
	,PARENTA=295
	,PARENTC=296
	,CORCHETEA=297
	,CORCHETEC=298
	,IGUAL=299
	,ARRAY=300
	,OPMENORIGUAL=301
	,OPMAYORIGUAL=302
	,OPDIFERENTE=303
	,OPMAYOR=304
	,OPMENOR=305
	,OPY=306
	,OPO=307
	,OPNO=308
	,VACIO=309


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::COMA=258;
const int YY_parse_CLASS::CTEREALSIGNO=259;
const int YY_parse_CLASS::CTEREALSINSIGNO=260;
const int YY_parse_CLASS::CTEENTSIGNO=261;
const int YY_parse_CLASS::CTEENTSINSIGNO=262;
const int YY_parse_CLASS::CTECADENA=263;
const int YY_parse_CLASS::PUNTOYCOMA=264;
const int YY_parse_CLASS::ELSE=265;
const int YY_parse_CLASS::IF=266;
const int YY_parse_CLASS::FOR=267;
const int YY_parse_CLASS::WHILE=268;
const int YY_parse_CLASS::DOUBLE=269;
const int YY_parse_CLASS::INT=270;
const int YY_parse_CLASS::STRING=271;
const int YY_parse_CLASS::CHAR=272;
const int YY_parse_CLASS::NEW=273;
const int YY_parse_CLASS::PUBLIC=274;
const int YY_parse_CLASS::CLASS=275;
const int YY_parse_CLASS::STATIC=276;
const int YY_parse_CLASS::VOID=277;
const int YY_parse_CLASS::ID=278;
const int YY_parse_CLASS::COMENTARIOSIMPLE=279;
const int YY_parse_CLASS::COMENTARIOCOMPLETO=280;
const int YY_parse_CLASS::OPMULT=281;
const int YY_parse_CLASS::OPSUM=282;
const int YY_parse_CLASS::OPSUS=283;
const int YY_parse_CLASS::OPDIV=284;
const int YY_parse_CLASS::OPASIGN=285;
const int YY_parse_CLASS::OPMOD=286;
const int YY_parse_CLASS::OPMASMAS=287;
const int YY_parse_CLASS::OPMENOSMENOS=288;
const int YY_parse_CLASS::OPPORASIGN=289;
const int YY_parse_CLASS::OPDIVASIGN=290;
const int YY_parse_CLASS::OPSUMASIGN=291;
const int YY_parse_CLASS::OPSUSASIGN=292;
const int YY_parse_CLASS::LLAVEA=293;
const int YY_parse_CLASS::LLAVEC=294;
const int YY_parse_CLASS::PARENTA=295;
const int YY_parse_CLASS::PARENTC=296;
const int YY_parse_CLASS::CORCHETEA=297;
const int YY_parse_CLASS::CORCHETEC=298;
const int YY_parse_CLASS::IGUAL=299;
const int YY_parse_CLASS::ARRAY=300;
const int YY_parse_CLASS::OPMENORIGUAL=301;
const int YY_parse_CLASS::OPMAYORIGUAL=302;
const int YY_parse_CLASS::OPDIFERENTE=303;
const int YY_parse_CLASS::OPMAYOR=304;
const int YY_parse_CLASS::OPMENOR=305;
const int YY_parse_CLASS::OPY=306;
const int YY_parse_CLASS::OPO=307;
const int YY_parse_CLASS::OPNO=308;
const int YY_parse_CLASS::VACIO=309;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		222
#define	YYFLAG		-32768
#define	YYNTBASE	55

#define YYTRANSLATE(x) ((unsigned)(x) <= 309 ? yytranslate[x] : 90)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     6,     8,    11,    13,    23,    24,    28,    31,    33,
    36,    39,    41,    43,    45,    47,    50,    53,    56,    59,
    63,    67,    71,    76,    81,    86,    89,    93,    95,    97,
    99,   101,   104,   107,   110,   113,   117,   121,   127,   131,
   136,   141,   146,   151,   154,   159,   162,   166,   168,   172,
   176,   179,   182,   186,   189,   192,   195,   198,   201,   205,
   207,   209,   215,   221,   225,   229,   232,   234,   236,   238,
   240,   242,   244,   246,   248,   250,   252,   254,   258,   260,
   264,   268,   272,   276,   280,   284,   289,   291,   293,   295,
   297,   299,   301,   303,   305,   311,   316,   324,   325,   329,
   336,   343,   350,   357,   360,   364,   365
};

static const short yyrhs[] = {    19,
    20,    23,    38,    56,     0,     1,     0,    57,    39,     0,
    39,     0,    19,    21,    22,    23,    40,    60,    41,    38,
    59,     0,     0,     1,    58,    59,     0,    65,    39,     0,
    39,     0,    61,    23,     0,    62,    23,     0,    16,     0,
    17,     0,    15,     0,    14,     0,    16,    64,     0,    17,
    64,     0,    15,    64,     0,    14,    64,     0,    42,    23,
    43,     0,    42,     6,    43,     0,    42,     7,    43,     0,
    63,    42,     6,    43,     0,    63,    42,     7,    43,     0,
    63,    42,    23,    43,     0,    42,    43,     0,    64,    42,
    43,     0,    66,     0,    83,     0,    86,     0,    87,     0,
    65,    66,     0,    65,    83,     0,    65,    86,     0,    65,
    87,     0,    61,    23,     9,     0,    62,    23,     9,     0,
    62,    23,    30,    69,     9,     0,    61,    68,     9,     0,
    61,    23,    67,     9,     0,    62,    23,    67,     9,     0,
    61,    68,    67,     9,     0,    62,    68,    67,     9,     0,
    68,     9,     0,    23,    30,    69,     9,     0,     3,    68,
     0,    67,     3,    68,     0,    70,     0,    23,    30,     8,
     0,    18,    61,    63,     0,    23,    71,     0,    23,    32,
     0,    23,    30,    72,     0,    23,    33,     0,    34,    72,
     0,    36,    72,     0,    37,    72,     0,    35,    72,     0,
    40,    72,    41,     0,    73,     0,    75,     0,    72,    77,
    40,    72,    41,     0,    72,    76,    40,    72,    41,     0,
    72,    77,    73,     0,    72,    77,    75,     0,    72,    75,
     0,    74,     0,    23,     0,     7,     0,     5,     0,     4,
     0,     6,     0,    27,     0,    28,     0,    26,     0,    29,
     0,    31,     0,    78,    80,    79,     0,    79,     0,    23,
    53,     8,     0,    23,    51,     8,     0,    23,    80,    23,
     0,    72,    82,    72,     0,    72,    81,    72,     0,    40,
    79,    41,     0,    53,    40,    79,    41,     0,    51,     0,
    52,     0,    48,     0,    44,     0,    46,     0,    50,     0,
    49,     0,    47,     0,    12,    40,    61,    68,    84,     0,
    12,    40,    68,    84,     0,     9,    78,     9,    70,    41,
    38,    59,     0,     0,     1,    85,    59,     0,    13,    40,
    78,    41,    38,    59,     0,    13,    40,    23,    41,    38,
    59,     0,    11,    40,    78,    41,    38,    59,     0,    11,
    40,    23,    41,    38,    59,     0,    87,    88,     0,    10,
    38,    59,     0,     0,     1,    89,    59,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    47,    49,    51,    52,    55,    57,    58,    59,    60,    63,
    64,    67,    68,    69,    70,    74,    75,    76,    77,    79,
    80,    81,    82,    83,    84,    87,    88,    91,    92,    93,
    94,    95,    96,    97,    98,   101,   102,   103,   104,   105,
   106,   107,   108,   109,   110,   112,   113,   115,   116,   119,
   122,   123,   124,   125,   128,   129,   130,   131,   134,   135,
   136,   137,   138,   139,   140,   141,   144,   145,   148,   149,
   152,   153,   155,   156,   158,   159,   160,   163,   164,   167,
   168,   169,   170,   171,   172,   173,   176,   177,   180,   181,
   184,   185,   186,   187,   190,   191,   193,   194,   195,   197,
   198,   202,   203,   204,   207,   208,   209
};

static const char * const yytname[] = {   "$","error","$illegal.","COMA","CTEREALSIGNO",
"CTEREALSINSIGNO","CTEENTSIGNO","CTEENTSINSIGNO","CTECADENA","PUNTOYCOMA","ELSE",
"IF","FOR","WHILE","DOUBLE","INT","STRING","CHAR","NEW","PUBLIC","CLASS","STATIC",
"VOID","ID","COMENTARIOSIMPLE","COMENTARIOCOMPLETO","OPMULT","OPSUM","OPSUS",
"OPDIV","OPASIGN","OPMOD","OPMASMAS","OPMENOSMENOS","OPPORASIGN","OPDIVASIGN",
"OPSUMASIGN","OPSUSASIGN","LLAVEA","LLAVEC","PARENTA","PARENTC","CORCHETEA",
"CORCHETEC","IGUAL","ARRAY","OPMENORIGUAL","OPMAYORIGUAL","OPDIFERENTE","OPMAYOR",
"OPMENOR","OPY","OPO","OPNO","VACIO","clase","clase2","metodomain","@1","cerrarbloque",
"parametro","tipo","tipovector","dimensionval","dimensionparam","bloque","declaracion",
"declaracion2","asignacion","valorvector","valorasigarit","operadoresaritasig",
"operacion","valoroperacion","constssinsignoarit","constsconsignoarit","operadoressumasus",
"operadoresarit","condicion","verificacion","operadoreslogconcat","operadoreslogcompa",
"operadoreslogarit","structfor","for2","@2","structwhile","strucif","strucifelse",
"@3",""
};
#endif

static const short yyr1[] = {     0,
    55,    55,    56,    56,    57,    58,    57,    59,    59,    60,
    60,    61,    61,    61,    61,    62,    62,    62,    62,    63,
    63,    63,    63,    63,    63,    64,    64,    65,    65,    65,
    65,    65,    65,    65,    65,    66,    66,    66,    66,    66,
    66,    66,    66,    66,    66,    67,    67,    68,    68,    69,
    70,    70,    70,    70,    71,    71,    71,    71,    72,    72,
    72,    72,    72,    72,    72,    72,    73,    73,    74,    74,
    75,    75,    76,    76,    77,    77,    77,    78,    78,    79,
    79,    79,    79,    79,    79,    79,    80,    80,    81,    81,
    82,    82,    82,    82,    83,    83,    84,    85,    84,    86,
    86,    87,    87,    87,    88,    89,    88
};

static const short yyr2[] = {     0,
     5,     1,     2,     1,     9,     0,     3,     2,     1,     2,
     2,     1,     1,     1,     1,     2,     2,     2,     2,     3,
     3,     3,     4,     4,     4,     2,     3,     1,     1,     1,
     1,     2,     2,     2,     2,     3,     3,     5,     3,     4,
     4,     4,     4,     2,     4,     2,     3,     1,     3,     3,
     2,     2,     3,     2,     2,     2,     2,     2,     3,     1,
     1,     5,     5,     3,     3,     2,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     3,     1,     3,
     3,     3,     3,     3,     3,     4,     1,     1,     1,     1,
     1,     1,     1,     1,     5,     4,     7,     0,     3,     6,
     6,     6,     6,     2,     3,     0,     3
};

static const short yydefact[] = {     0,
     2,     0,     0,     0,     0,     6,     0,     4,     1,     0,
     0,     0,     3,     0,     0,     0,    15,    14,    12,    13,
     0,     9,     7,     0,     0,     0,    28,     0,    48,    29,
    30,     0,     0,     0,     0,     0,     0,    19,    18,    16,
    17,     0,    52,    54,     0,     0,     0,     0,    51,     0,
     0,     0,     0,     8,    32,    33,    34,     0,    44,   106,
     0,   104,     0,    71,    70,    72,    69,    68,     0,     0,
     0,    60,    67,    61,     0,    79,    15,    14,    12,    13,
     0,     0,     0,    68,     0,    26,     0,    49,     0,    68,
     0,     0,    53,    55,    58,    56,    57,     0,    36,     0,
     0,    39,     0,    37,     0,     0,     0,     0,     0,     0,
     0,    87,    88,     0,     0,    68,     0,     0,     0,    75,
    73,    74,    76,    77,    90,    91,    94,    89,    93,    92,
    66,     0,     0,     0,     0,     0,    87,     0,     0,    98,
     0,    96,     0,     0,    27,     0,     0,    45,    46,     0,
    40,    42,     0,    41,    43,   107,   105,     0,     0,     0,
     0,    81,    80,    82,    59,    85,     0,     0,     0,    64,
    65,    84,    83,     0,    78,    95,     0,     0,     0,     0,
     0,    50,    47,    38,     0,    10,    11,   103,    86,     0,
     0,   102,    99,     0,   101,   100,     0,     0,     0,     0,
     0,    63,    62,     0,     0,    21,    22,    20,     0,     0,
     0,     5,     0,     0,    23,    24,    25,     0,    97,     0,
     0,     0
};

static const short yydefgoto[] = {   220,
     9,    10,    11,    23,   158,    24,    25,   182,    38,    26,
    27,   101,    28,    92,    29,    49,    71,    72,    73,    74,
   132,   133,    75,    76,   115,   134,   135,    30,   142,   177,
    31,    32,    62,   108
};

static const short yypact[] = {    22,
-32768,    -6,    -4,   -21,    27,-32768,     8,-32768,-32768,    -9,
   296,    14,-32768,     3,     7,    10,     6,     6,     6,     6,
   317,-32768,-32768,    34,    53,   309,-32768,    75,-32768,-32768,
-32768,   166,    71,    33,   322,    47,    62,    74,    74,    74,
    74,   226,-32768,-32768,    92,    92,    92,    92,-32768,   261,
    12,   269,   104,-32768,-32768,-32768,-32768,   183,-32768,-32768,
    81,-32768,    84,-32768,-32768,-32768,-32768,   195,    55,    85,
   116,-32768,-32768,-32768,    38,-32768,-32768,-32768,-32768,-32768,
   325,   115,    15,   276,    89,-32768,    88,-32768,   158,-32768,
    92,   137,   256,   256,   256,   256,   256,   115,-32768,   246,
    65,-32768,    66,-32768,   226,   100,   114,   296,   296,   200,
   110,   142,-32768,   143,   130,   117,   108,   118,    55,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   121,   252,    92,    92,   147,-32768,    55,    15,-32768,
    55,-32768,   149,   163,-32768,   161,   182,-32768,-32768,   115,
-32768,-32768,   203,-32768,-32768,-32768,-32768,   178,   184,   205,
   296,-32768,-32768,-32768,-32768,-32768,   180,    92,    92,-32768,
-32768,   256,   256,   296,-32768,-32768,   296,    -7,   296,   296,
    19,   193,-32768,-32768,   199,-32768,-32768,-32768,-32768,   198,
   214,-32768,-32768,   215,-32768,-32768,   218,   220,   222,    95,
   296,-32768,-32768,   333,   227,-32768,-32768,-32768,   224,   230,
   231,-32768,    92,   233,-32768,-32768,-32768,   296,-32768,   277,
   288,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,-32768,   -97,-32768,   -22,   179,-32768,   172,-32768,
   250,   228,   -17,   185,   106,-32768,   -42,   181,-32768,   -62,
-32768,-32768,   -35,   -47,   -65,-32768,-32768,   289,   177,-32768,
   292,   304,-32768,-32768
};


#define	YYLAST		370


static const short yytable[] = {    93,
    85,   194,    94,    95,    96,    97,    51,    53,   131,   138,
   156,   157,    82,     3,    98,   140,     5,    83,     4,   138,
   102,   118,     1,   141,   197,   198,   117,     6,    12,    13,
   131,   131,   131,   131,   131,    33,    64,    65,    66,    67,
     2,   199,    34,   137,   113,     7,    35,    37,   147,    36,
    64,    65,    66,    67,   131,    68,    50,    93,    64,    65,
    66,    67,    93,   188,   139,     8,   146,   150,   150,    84,
   171,   167,    69,   151,   152,    52,   192,   116,   136,   193,
   149,   195,   196,    59,   131,    70,    69,   159,   137,   113,
   175,   172,   173,    63,    69,    64,    65,    66,    67,    70,
   209,   210,   150,   212,    86,   178,    98,    70,   154,   131,
   131,    64,   138,    66,    90,    87,   150,   211,   109,    64,
   219,    66,   155,   110,   119,   190,   191,   131,   131,   144,
   145,    91,   183,   120,   121,   122,   123,    81,   124,   137,
   113,   120,   121,   122,   123,   148,   124,   161,   165,   162,
   163,   125,   164,   126,   127,   128,   129,   130,   166,   125,
   168,   126,   127,   128,   129,   130,    60,   112,   113,   114,
    93,    77,    78,    79,    80,    61,   -31,   -31,   -31,   -31,
   -31,   -31,   -31,    60,   174,    64,   179,    66,   -31,    39,
    40,    41,    61,   -35,   -35,   -35,   -35,   -35,   -35,   -35,
   180,    64,   181,    66,   -31,   -35,   186,   120,   121,   122,
   123,   184,   124,    17,    18,    19,    20,    64,   185,    66,
   189,   -35,   165,   120,   121,   122,   123,   187,   124,    64,
    65,    66,    67,    88,   200,   111,   201,   204,   202,   120,
   121,   122,   123,    89,   124,   112,   113,   114,    90,    64,
    65,    66,    67,    88,   203,    64,    65,    66,    67,    64,
   206,    66,   207,    98,   208,    91,   215,   214,    90,    99,
   218,    98,   216,   217,    90,    55,   221,   104,   103,   106,
   107,   120,   121,   122,   123,    91,   124,   222,   160,   153,
   100,   169,    43,    44,    45,    46,    47,    48,   105,   205,
    43,    44,    45,    46,    47,    48,    14,    15,    16,    17,
    18,    19,    20,   170,    56,   176,   143,    57,    21,    14,
    15,    16,    17,    18,    19,    20,   112,   113,   114,    58,
     0,    21,     0,     0,    22,    77,    78,    79,    80,     0,
     0,     0,     0,     0,    81,     0,    42,    54,    43,    44,
    45,    46,    47,    48,   100,     0,    43,    44,    45,    46,
    47,    48,   213,     0,    43,    44,    45,    46,    47,    48
};

static const short yycheck[] = {    42,
    36,     9,    45,    46,    47,    48,    24,    25,    71,    75,
   108,   109,    35,    20,     3,     1,    38,    35,    23,    85,
     9,    69,     1,     9,     6,     7,    69,     1,    21,    39,
    93,    94,    95,    96,    97,    22,     4,     5,     6,     7,
    19,    23,    40,    51,    52,    19,    40,    42,    91,    40,
     4,     5,     6,     7,   117,    23,    23,   100,     4,     5,
     6,     7,   105,   161,    82,    39,    89,     3,     3,    23,
   133,   119,    40,     9,     9,    23,   174,    23,    41,   177,
    98,   179,   180,     9,   147,    53,    40,   110,    51,    52,
   138,   134,   135,    23,    40,     4,     5,     6,     7,    53,
     6,     7,     3,   201,    43,   141,     3,    53,     9,   172,
   173,     4,   178,     6,    23,    42,     3,    23,    38,     4,
   218,     6,     9,    40,    40,   168,   169,   190,   191,    41,
    43,    40,   150,    26,    27,    28,    29,    23,    31,    51,
    52,    26,    27,    28,    29,     9,    31,    38,    41,     8,
     8,    44,    23,    46,    47,    48,    49,    50,    41,    44,
    40,    46,    47,    48,    49,    50,     1,    51,    52,    53,
   213,    14,    15,    16,    17,    10,    11,    12,    13,    14,
    15,    16,    17,     1,    38,     4,    38,     6,    23,    18,
    19,    20,    10,    11,    12,    13,    14,    15,    16,    17,
    38,     4,    42,     6,    39,    23,    23,    26,    27,    28,
    29,     9,    31,    14,    15,    16,    17,     4,    41,     6,
    41,    39,    41,    26,    27,    28,    29,    23,    31,     4,
     5,     6,     7,     8,    42,    41,    38,    23,    41,    26,
    27,    28,    29,    18,    31,    51,    52,    53,    23,     4,
     5,     6,     7,     8,    41,     4,     5,     6,     7,     4,
    43,     6,    43,     3,    43,    40,    43,    41,    23,     9,
    38,     3,    43,    43,    23,    26,     0,     9,    51,    52,
    53,    26,    27,    28,    29,    40,    31,     0,   110,   105,
    30,    40,    32,    33,    34,    35,    36,    37,    30,   194,
    32,    33,    34,    35,    36,    37,    11,    12,    13,    14,
    15,    16,    17,   133,    26,   139,    41,    26,    23,    11,
    12,    13,    14,    15,    16,    17,    51,    52,    53,    26,
    -1,    23,    -1,    -1,    39,    14,    15,    16,    17,    -1,
    -1,    -1,    -1,    -1,    23,    -1,    30,    39,    32,    33,
    34,    35,    36,    37,    30,    -1,    32,    33,    34,    35,
    36,    37,    30,    -1,    32,    33,    34,    35,    36,    37
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 2:
#line 49 "LAB01-Nieto-Utria-Gonzalez.y"
{yyerrok;yyclearin;;
    break;}
case 6:
#line 57 "LAB01-Nieto-Utria-Gonzalez.y"
{yyerrok;yyclearin;;
    break;}
case 98:
#line 194 "LAB01-Nieto-Utria-Gonzalez.y"
{yyerrok;yyclearin;;
    break;}
case 106:
#line 208 "LAB01-Nieto-Utria-Gonzalez.y"
{yyerrok;yyclearin;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 213 "LAB01-Nieto-Utria-Gonzalez.y"
