#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from LAB01-Nieto-Utria-Gonzalez.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "LAB01-Nieto-Utria-Gonzalez.y"

#include <stdio.h>
#include <string.h>


extern int contLineas;

void yyerror(const char *str)
{
    fprintf(stderr, "error: %s, %d\n", str, contLineas);
}

int yywrap()
{
    return 1;
}

int main(int argc, char* argv[])
{
    extern FILE *yyin, *yyout;
  
    yyin = fopen("entrada.java", "r");
  
    yyout = fopen("salida.txt","w");

    while(!feof(yyin)){
    yyparse();
    }
}

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	COMA	258
#define	CTEREALSIGNO	259
#define	CTEREALSINSIGNO	260
#define	CTEENTSIGNO	261
#define	CTEENTSINSIGNO	262
#define	CTECADENA	263
#define	PUNTOYCOMA	264
#define	ELSE	265
#define	IF	266
#define	FOR	267
#define	WHILE	268
#define	DOUBLE	269
#define	INT	270
#define	STRING	271
#define	CHAR	272
#define	NEW	273
#define	PUBLIC	274
#define	CLASS	275
#define	STATIC	276
#define	VOID	277
#define	ID	278
#define	COMENTARIOSIMPLE	279
#define	COMENTARIOCOMPLETO	280
#define	OPMULT	281
#define	OPSUM	282
#define	OPSUS	283
#define	OPDIV	284
#define	OPASIGN	285
#define	OPMOD	286
#define	OPMASMAS	287
#define	OPMENOSMENOS	288
#define	OPPORASIGN	289
#define	OPDIVASIGN	290
#define	OPSUMASIGN	291
#define	OPSUSASIGN	292
#define	LLAVEA	293
#define	LLAVEC	294
#define	PARENTA	295
#define	PARENTC	296
#define	CORCHETEA	297
#define	CORCHETEC	298
#define	IGUAL	299
#define	ARRAY	300
#define	OPMENORIGUAL	301
#define	OPMAYORIGUAL	302
#define	OPDIFERENTE	303
#define	OPMAYOR	304
#define	OPMENOR	305
#define	OPY	306
#define	OPO	307
#define	OPNO	308
#define	VACIO	309


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int COMA;
static const int CTEREALSIGNO;
static const int CTEREALSINSIGNO;
static const int CTEENTSIGNO;
static const int CTEENTSINSIGNO;
static const int CTECADENA;
static const int PUNTOYCOMA;
static const int ELSE;
static const int IF;
static const int FOR;
static const int WHILE;
static const int DOUBLE;
static const int INT;
static const int STRING;
static const int CHAR;
static const int NEW;
static const int PUBLIC;
static const int CLASS;
static const int STATIC;
static const int VOID;
static const int ID;
static const int COMENTARIOSIMPLE;
static const int COMENTARIOCOMPLETO;
static const int OPMULT;
static const int OPSUM;
static const int OPSUS;
static const int OPDIV;
static const int OPASIGN;
static const int OPMOD;
static const int OPMASMAS;
static const int OPMENOSMENOS;
static const int OPPORASIGN;
static const int OPDIVASIGN;
static const int OPSUMASIGN;
static const int OPSUSASIGN;
static const int LLAVEA;
static const int LLAVEC;
static const int PARENTA;
static const int PARENTC;
static const int CORCHETEA;
static const int CORCHETEC;
static const int IGUAL;
static const int ARRAY;
static const int OPMENORIGUAL;
static const int OPMAYORIGUAL;
static const int OPDIFERENTE;
static const int OPMAYOR;
static const int OPMENOR;
static const int OPY;
static const int OPO;
static const int OPNO;
static const int VACIO;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,COMA=258
	,CTEREALSIGNO=259
	,CTEREALSINSIGNO=260
	,CTEENTSIGNO=261
	,CTEENTSINSIGNO=262
	,CTECADENA=263
	,PUNTOYCOMA=264
	,ELSE=265
	,IF=266
	,FOR=267
	,WHILE=268
	,DOUBLE=269
	,INT=270
	,STRING=271
	,CHAR=272
	,NEW=273
	,PUBLIC=274
	,CLASS=275
	,STATIC=276
	,VOID=277
	,ID=278
	,COMENTARIOSIMPLE=279
	,COMENTARIOCOMPLETO=280
	,OPMULT=281
	,OPSUM=282
	,OPSUS=283
	,OPDIV=284
	,OPASIGN=285
	,OPMOD=286
	,OPMASMAS=287
	,OPMENOSMENOS=288
	,OPPORASIGN=289
	,OPDIVASIGN=290
	,OPSUMASIGN=291
	,OPSUSASIGN=292
	,LLAVEA=293
	,LLAVEC=294
	,PARENTA=295
	,PARENTC=296
	,CORCHETEA=297
	,CORCHETEC=298
	,IGUAL=299
	,ARRAY=300
	,OPMENORIGUAL=301
	,OPMAYORIGUAL=302
	,OPDIFERENTE=303
	,OPMAYOR=304
	,OPMENOR=305
	,OPY=306
	,OPO=307
	,OPNO=308
	,VACIO=309


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::COMA=258;
const int YY_parse_CLASS::CTEREALSIGNO=259;
const int YY_parse_CLASS::CTEREALSINSIGNO=260;
const int YY_parse_CLASS::CTEENTSIGNO=261;
const int YY_parse_CLASS::CTEENTSINSIGNO=262;
const int YY_parse_CLASS::CTECADENA=263;
const int YY_parse_CLASS::PUNTOYCOMA=264;
const int YY_parse_CLASS::ELSE=265;
const int YY_parse_CLASS::IF=266;
const int YY_parse_CLASS::FOR=267;
const int YY_parse_CLASS::WHILE=268;
const int YY_parse_CLASS::DOUBLE=269;
const int YY_parse_CLASS::INT=270;
const int YY_parse_CLASS::STRING=271;
const int YY_parse_CLASS::CHAR=272;
const int YY_parse_CLASS::NEW=273;
const int YY_parse_CLASS::PUBLIC=274;
const int YY_parse_CLASS::CLASS=275;
const int YY_parse_CLASS::STATIC=276;
const int YY_parse_CLASS::VOID=277;
const int YY_parse_CLASS::ID=278;
const int YY_parse_CLASS::COMENTARIOSIMPLE=279;
const int YY_parse_CLASS::COMENTARIOCOMPLETO=280;
const int YY_parse_CLASS::OPMULT=281;
const int YY_parse_CLASS::OPSUM=282;
const int YY_parse_CLASS::OPSUS=283;
const int YY_parse_CLASS::OPDIV=284;
const int YY_parse_CLASS::OPASIGN=285;
const int YY_parse_CLASS::OPMOD=286;
const int YY_parse_CLASS::OPMASMAS=287;
const int YY_parse_CLASS::OPMENOSMENOS=288;
const int YY_parse_CLASS::OPPORASIGN=289;
const int YY_parse_CLASS::OPDIVASIGN=290;
const int YY_parse_CLASS::OPSUMASIGN=291;
const int YY_parse_CLASS::OPSUSASIGN=292;
const int YY_parse_CLASS::LLAVEA=293;
const int YY_parse_CLASS::LLAVEC=294;
const int YY_parse_CLASS::PARENTA=295;
const int YY_parse_CLASS::PARENTC=296;
const int YY_parse_CLASS::CORCHETEA=297;
const int YY_parse_CLASS::CORCHETEC=298;
const int YY_parse_CLASS::IGUAL=299;
const int YY_parse_CLASS::ARRAY=300;
const int YY_parse_CLASS::OPMENORIGUAL=301;
const int YY_parse_CLASS::OPMAYORIGUAL=302;
const int YY_parse_CLASS::OPDIFERENTE=303;
const int YY_parse_CLASS::OPMAYOR=304;
const int YY_parse_CLASS::OPMENOR=305;
const int YY_parse_CLASS::OPY=306;
const int YY_parse_CLASS::OPO=307;
const int YY_parse_CLASS::OPNO=308;
const int YY_parse_CLASS::VACIO=309;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		209
#define	YYFLAG		-32768
#define	YYNTBASE	55

#define YYTRANSLATE(x) ((unsigned)(x) <= 309 ? yytranslate[x] : 88)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     6,     8,    11,    13,    23,    25,    28,    30,    33,
    36,    38,    40,    42,    44,    47,    50,    53,    56,    60,
    64,    68,    73,    78,    83,    86,    90,    92,    94,    96,
    98,   101,   104,   107,   110,   112,   116,   120,   124,   128,
   133,   138,   143,   148,   151,   154,   158,   160,   164,   166,
   170,   173,   176,   180,   183,   186,   189,   192,   195,   199,
   201,   203,   209,   215,   219,   223,   226,   228,   230,   232,
   234,   236,   238,   240,   242,   244,   246,   248,   252,   254,
   258,   262,   266,   270,   274,   279,   281,   283,   285,   287,
   289,   291,   293,   295,   302,   308,   315,   318,   320,   327,
   334,   341,   348,   351
};

static const short yyrhs[] = {    19,
    20,    23,    38,    56,     0,     1,     0,    57,    39,     0,
    39,     0,    19,    21,    22,    23,    40,    59,    41,    38,
    58,     0,     1,     0,    64,    39,     0,    39,     0,    60,
    23,     0,    61,    23,     0,    16,     0,    17,     0,    15,
     0,    14,     0,    16,    63,     0,    17,    63,     0,    15,
    63,     0,    14,    63,     0,    42,    23,    43,     0,    42,
     6,    43,     0,    42,     7,    43,     0,    62,    42,     6,
    43,     0,    62,    42,     7,    43,     0,    62,    42,    23,
    43,     0,    42,    43,     0,    63,    42,    43,     0,    65,
     0,    82,     0,    85,     0,    86,     0,    64,    65,     0,
    64,    82,     0,    64,    85,     0,    64,    86,     0,     1,
     0,    60,    23,     9,     0,    61,    23,     9,     0,    61,
    67,     9,     0,    60,    67,     9,     0,    60,    23,    66,
     9,     0,    61,    23,    66,     9,     0,    60,    67,    66,
     9,     0,    61,    67,    66,     9,     0,    67,     9,     0,
     3,    67,     0,    66,     3,    67,     0,    69,     0,    23,
    30,     8,     0,    68,     0,    18,    60,    62,     0,    23,
    70,     0,    23,    32,     0,    23,    30,    71,     0,    23,
    33,     0,    34,    71,     0,    36,    71,     0,    37,    71,
     0,    35,    71,     0,    40,    71,    41,     0,    72,     0,
    74,     0,    71,    76,    40,    71,    41,     0,    71,    75,
    40,    71,    41,     0,    71,    76,    72,     0,    71,    76,
    74,     0,    71,    74,     0,    73,     0,    23,     0,     7,
     0,     5,     0,     4,     0,     6,     0,    27,     0,    28,
     0,    26,     0,    29,     0,    31,     0,    77,    79,    78,
     0,    78,     0,    23,    81,    71,     0,    23,    80,     8,
     0,    23,    80,    71,     0,    23,    79,    23,     0,    40,
    78,    41,     0,    53,    40,    78,    41,     0,    51,     0,
    52,     0,    48,     0,    44,     0,    46,     0,    50,     0,
    49,     0,    47,     0,    12,    40,    60,    67,     9,    83,
     0,    12,    40,    67,     9,    83,     0,    77,     9,    69,
    41,    38,    84,     0,    64,    39,     0,    39,     0,    13,
    40,    77,    41,    38,    58,     0,    13,    40,    23,    41,
    38,    58,     0,    11,    40,    77,    41,    38,    58,     0,
    11,    40,    23,    41,    38,    58,     0,    86,    87,     0,
    10,    38,    58,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    41,    43,    45,    46,    49,    51,    53,    54,    57,    58,
    61,    62,    63,    64,    68,    69,    70,    71,    73,    74,
    75,    76,    77,    78,    81,    82,    85,    86,    87,    88,
    89,    90,    91,    92,    93,    96,    97,    98,    99,   100,
   101,   102,   103,   104,   107,   108,   110,   111,   112,   115,
   118,   119,   120,   121,   124,   125,   126,   127,   130,   131,
   132,   133,   134,   135,   136,   137,   140,   141,   144,   145,
   148,   149,   151,   152,   154,   155,   156,   159,   159,   161,
   162,   163,   164,   165,   166,   169,   170,   173,   174,   177,
   178,   179,   180,   183,   184,   186,   188,   189,   191,   192,
   195,   196,   197,   200
};

static const char * const yytname[] = {   "$","error","$illegal.","COMA","CTEREALSIGNO",
"CTEREALSINSIGNO","CTEENTSIGNO","CTEENTSINSIGNO","CTECADENA","PUNTOYCOMA","ELSE",
"IF","FOR","WHILE","DOUBLE","INT","STRING","CHAR","NEW","PUBLIC","CLASS","STATIC",
"VOID","ID","COMENTARIOSIMPLE","COMENTARIOCOMPLETO","OPMULT","OPSUM","OPSUS",
"OPDIV","OPASIGN","OPMOD","OPMASMAS","OPMENOSMENOS","OPPORASIGN","OPDIVASIGN",
"OPSUMASIGN","OPSUSASIGN","LLAVEA","LLAVEC","PARENTA","PARENTC","CORCHETEA",
"CORCHETEC","IGUAL","ARRAY","OPMENORIGUAL","OPMAYORIGUAL","OPDIFERENTE","OPMAYOR",
"OPMENOR","OPY","OPO","OPNO","VACIO","clase","clase2","metodomain","cerrarbloque",
"parametro","tipo","tipovector","dimensionval","dimensionparam","bloque","declaracion",
"declaracion2","asignacion","valorvector","valorasigarit","operadoresaritasig",
"operacion","valoroperacion","constssinsignoarit","constsconsignoarit","operadoressumasus",
"operadoresarit","condicion","verificacion","operadoreslogconcat","operadoreslogcompa",
"operadoreslogarit","structfor","for2","for3","structwhile","strucif","strucifelse",
""
};
#endif

static const short yyr1[] = {     0,
    55,    55,    56,    56,    57,    57,    58,    58,    59,    59,
    60,    60,    60,    60,    61,    61,    61,    61,    62,    62,
    62,    62,    62,    62,    63,    63,    64,    64,    64,    64,
    64,    64,    64,    64,    64,    65,    65,    65,    65,    65,
    65,    65,    65,    65,    66,    66,    67,    67,    67,    68,
    69,    69,    69,    69,    70,    70,    70,    70,    71,    71,
    71,    71,    71,    71,    71,    71,    72,    72,    73,    73,
    74,    74,    75,    75,    76,    76,    76,    77,    77,    78,
    78,    78,    78,    78,    78,    79,    79,    80,    80,    81,
    81,    81,    81,    82,    82,    83,    84,    84,    85,    85,
    86,    86,    86,    87
};

static const short yyr2[] = {     0,
     5,     1,     2,     1,     9,     1,     2,     1,     2,     2,
     1,     1,     1,     1,     2,     2,     2,     2,     3,     3,
     3,     4,     4,     4,     2,     3,     1,     1,     1,     1,
     2,     2,     2,     2,     1,     3,     3,     3,     3,     4,
     4,     4,     4,     2,     2,     3,     1,     3,     1,     3,
     2,     2,     3,     2,     2,     2,     2,     2,     3,     1,
     1,     5,     5,     3,     3,     2,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     3,     1,     3,
     3,     3,     3,     3,     4,     1,     1,     1,     1,     1,
     1,     1,     1,     6,     5,     6,     2,     1,     6,     6,
     6,     6,     2,     3
};

static const short yydefact[] = {     0,
     2,     0,     0,     0,     0,     6,     0,     4,     1,     0,
     0,     3,     0,     0,     0,    14,    13,    11,    12,     0,
     0,     0,     0,    18,    17,    15,    16,     0,     9,    10,
    25,     0,     0,    26,    35,     0,     0,     0,     0,     0,
     8,     5,     0,     0,     0,    27,     0,    49,    47,    28,
    29,    30,     0,     0,     0,    14,    13,    11,    12,     0,
     0,    52,    54,     0,     0,     0,     0,    51,     0,     0,
     0,     0,     7,    31,    32,    33,    34,    44,     0,   103,
     0,     0,     0,     0,    79,     0,     0,     0,     0,     0,
    50,    71,    70,    72,    69,    48,    68,     0,    53,    60,
    67,    61,    55,    58,    56,    57,     0,    36,     0,    39,
     0,    37,     0,    38,     0,     0,     0,    89,    90,    93,
    88,    92,    91,    86,    87,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    75,    73,    74,    76,    77,    66,     0,     0,
    45,     0,    40,    42,    41,    43,   104,     0,    83,    81,
    82,    80,    84,     0,     0,    78,     0,     0,    95,     0,
     0,    20,    21,    19,     0,     0,     0,    59,     0,     0,
    64,    65,    46,   102,    85,   101,    94,     0,   100,    99,
    22,    23,    24,     0,     0,     0,     0,    63,    62,     0,
     0,     0,    98,     0,    96,    97,     0,     0,     0
};

static const short yydefgoto[] = {   207,
     9,    10,    42,    20,    43,    44,    91,    24,    45,    46,
   109,    47,    48,    49,    68,    99,   100,   101,   102,   149,
   150,   168,    85,   126,   127,   128,    50,   169,   205,    51,
    52,    80
};

static const short yypact[] = {    28,
-32768,     2,     0,   -12,    27,-32768,     9,-32768,-32768,    18,
     5,-32768,    46,    36,   187,    49,    49,    49,    49,    37,
    75,    77,    99,    80,    80,    80,    80,   106,-32768,-32768,
-32768,   103,    69,-32768,-32768,   108,   115,   118,   228,   262,
-32768,-32768,   169,   171,   223,-32768,   176,-32768,-32768,-32768,
-32768,   186,    -9,    79,    65,-32768,-32768,-32768,-32768,   164,
    35,-32768,-32768,   172,   172,   172,   172,-32768,   188,    68,
   196,   127,-32768,-32768,-32768,-32768,   186,-32768,   178,-32768,
   217,   116,   174,   -17,-32768,   175,   206,   230,    38,    26,
   218,-32768,-32768,-32768,-32768,-32768,-32768,   172,   182,-32768,
-32768,-32768,   182,   182,   182,   182,   175,-32768,   131,-32768,
   132,-32768,   144,-32768,   154,    69,   181,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,   204,   167,   172,   239,   229,
   116,   234,   116,   264,   116,   246,   255,   258,   265,   266,
    30,    97,-32768,-32768,-32768,-32768,-32768,-32768,   271,   177,
-32768,   175,-32768,-32768,-32768,-32768,-32768,    69,-32768,-32768,
   182,   182,-32768,   269,    69,-32768,   116,     4,-32768,    69,
    69,-32768,-32768,-32768,   272,   273,   274,-32768,   172,   172,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   289,-32768,-32768,
-32768,-32768,-32768,   123,   139,   270,   277,-32768,-32768,   172,
   275,    98,-32768,   236,-32768,-32768,   314,   319,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,  -106,-32768,     6,   305,-32768,   114,   119,   -45,
   185,   -35,-32768,   134,-32768,   -60,   173,-32768,   -88,-32768,
-32768,    -5,   -70,   -64,-32768,-32768,   -44,   157,-32768,   -43,
   -42,-32768
};


#define	YYLAST		324


static const short yytable[] = {    74,
    75,    76,    77,   103,   104,   105,   106,    70,    72,   157,
   148,   130,   188,    81,   148,   148,   148,   148,    87,   133,
    21,     3,     4,   132,   133,     5,    13,     6,     1,    11,
    82,   138,   139,   124,   125,   175,   176,   142,    92,    93,
    94,    95,    96,    83,    60,     7,     2,    84,   140,    89,
   134,   184,   177,   148,   124,   125,    12,    97,   186,    86,
   164,   182,   166,   189,   190,     8,   161,   162,    14,    35,
   107,   151,   148,   148,    98,    15,   110,    28,   137,    36,
    37,    38,    16,    17,    18,    19,    39,    88,   124,   125,
    23,    40,    56,    57,    58,    59,    39,    29,    35,    30,
    92,    40,    94,   133,    82,   148,   148,    41,    36,    37,
    38,    16,    17,    18,    19,    39,   183,    83,   194,   195,
    40,    32,   143,   144,   145,   146,    92,   147,    94,   107,
    25,    26,    27,   152,   152,   114,   203,   178,   129,   153,
   154,    31,    92,    33,    94,    34,   152,    53,   143,   144,
   145,   146,   155,   147,    54,    82,   152,    55,    74,    75,
    76,    77,   156,   198,   143,   144,   145,   146,    83,   147,
    92,    93,    94,    95,   160,    92,    93,    94,    95,   199,
    92,    93,    94,    95,    78,    92,    39,    94,    39,    97,
   107,    69,    39,    71,    97,    79,   108,    40,   107,    97,
    16,    17,    18,    19,   112,    90,    98,   143,   144,   145,
   146,    98,   147,   131,   135,   116,   180,    61,   158,    62,
    63,    64,    65,    66,    67,    61,   159,    62,    63,    64,
    65,    66,    67,    36,    37,    38,    16,    17,    18,    19,
    39,    56,    57,    58,    59,    40,    36,    37,    38,    16,
    17,    18,    19,    39,   111,   113,   115,   117,    40,   141,
   118,    73,   119,   120,   121,   122,   123,   124,   125,   163,
   136,   165,   167,   118,   206,   119,   120,   121,   122,   123,
   124,   125,   118,   170,   119,   120,   121,   122,   123,   124,
   125,    61,   171,    62,    63,    64,    65,    66,    67,   200,
   172,    62,    63,    64,    65,    66,    67,   173,   174,   185,
   179,   196,   202,   208,   191,   192,   193,   201,   209,    22,
   204,   197,   181,   187
};

static const short yycheck[] = {    45,
    45,    45,    45,    64,    65,    66,    67,    43,    44,   116,
    99,    82,     9,    23,   103,   104,   105,   106,    54,    84,
    15,    20,    23,    41,    89,    38,    22,     1,     1,    21,
    40,     6,     7,    51,    52,     6,     7,    98,     4,     5,
     6,     7,     8,    53,    39,    19,    19,    53,    23,    55,
    86,   158,    23,   142,    51,    52,    39,    23,   165,    54,
   131,   150,   133,   170,   171,    39,   127,   128,    23,     1,
     3,   107,   161,   162,    40,    40,     9,    41,    41,    11,
    12,    13,    14,    15,    16,    17,    18,    23,    51,    52,
    42,    23,    14,    15,    16,    17,    18,    23,     1,    23,
     4,    23,     6,   168,    40,   194,   195,    39,    11,    12,
    13,    14,    15,    16,    17,    18,   152,    53,   179,   180,
    23,    42,    26,    27,    28,    29,     4,    31,     6,     3,
    17,    18,    19,     3,     3,     9,    39,    41,    23,     9,
     9,    43,     4,    38,     6,    43,     3,    40,    26,    27,
    28,    29,     9,    31,    40,    40,     3,    40,   204,   204,
   204,   204,     9,    41,    26,    27,    28,    29,    53,    31,
     4,     5,     6,     7,     8,     4,     5,     6,     7,    41,
     4,     5,     6,     7,     9,     4,    18,     6,    18,    23,
     3,    23,    18,    23,    23,    10,     9,    23,     3,    23,
    14,    15,    16,    17,     9,    42,    40,    26,    27,    28,
    29,    40,    31,    40,     9,    38,    40,    30,    38,    32,
    33,    34,    35,    36,    37,    30,    23,    32,    33,    34,
    35,    36,    37,    11,    12,    13,    14,    15,    16,    17,
    18,    14,    15,    16,    17,    23,    11,    12,    13,    14,
    15,    16,    17,    18,    70,    71,    72,    41,    23,    42,
    44,    39,    46,    47,    48,    49,    50,    51,    52,    41,
    41,    38,     9,    44,    39,    46,    47,    48,    49,    50,
    51,    52,    44,    38,    46,    47,    48,    49,    50,    51,
    52,    30,    38,    32,    33,    34,    35,    36,    37,    30,
    43,    32,    33,    34,    35,    36,    37,    43,    43,    41,
    40,    23,    38,     0,    43,    43,    43,    41,     0,    15,
   202,   188,   150,   167
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 2:
#line 43 "LAB01-Nieto-Utria-Gonzalez.y"
{yyerrok;yyclearin;;
    break;}
case 6:
#line 51 "LAB01-Nieto-Utria-Gonzalez.y"
{yyerrok;yyclearin;;
    break;}
case 35:
#line 93 "LAB01-Nieto-Utria-Gonzalez.y"
{yyerrok;yyclearin;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 204 "LAB01-Nieto-Utria-Gonzalez.y"
